# Generated by Django 5.1.7 on 2025-03-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_restaurant_restuarant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datetime', models.DateTimeField()),
                ('restuarant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.restaurant')),
            ],
        ),
    ]
