# Generated by Django 5.1.7 on 2025-03-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restuarant_type',
            new_name='restaurant_type',
        ),
    ]
