# Generated by Django 5.1.7 on 2025-03-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_rating_restaurant_alter_sale_restuarant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
